Website = "https://github.com/weijia/go-stock-server"

[Details]
Icon = "build-out/gui_icon.png"
Name = "StockServerGUI"
ID = "com.stock.server.gui"
# Version 和 Build 由 CI 的 -appVersion/-appBuild 参数覆盖
